### ISSUE TITLE
Generator generates routes with zero duration

### ISSUE THREAD

**Issue by mehdisadeghi** [n7a235/service.routing#26]
Some generator results do not conform to the spec of `directions` function. They have zero duration and zero distance. If this is intended we have to update the spec to allow zero values for these two keys. 

``` {
    "code": "Ok",
    "waypoints": [
      {
        "name": "wonderland",
        "location": [
          1,
          1
        ]
      },
      {
        "name": "wonderland",
        "location": [
          2,
          2
        ]
      }
    ],
    "routes": [
      {
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [
              0.9036815166473389,
              1
            ]
          ]
        },
        "duration": 0,
        "distance": 0,
        "weight": 0,
        "weight-name": "routability",
        "legs": []
      }
    ]
  }```

**Comment by mehdisadeghi** [comment]
The same things happens if the start and end coordinates are the same.

**Comment by mehdisadeghi** [comment]
@carocad btw I just realized that mapbox returns zero if start and end waypoints are the same. Therefore I think duration and distance are greater than or equal to zero.

**Comment by carocad** [comment]
@mehdisadeghi I think this is an underlying bug in my implementations of the `directions` function. So probably this is a deeper and more problematic bug :(

On the other hand, you are right. The distance and duration can be zero if the start and end are the same. Which is not the case in your example so that worries me a bit. The other problem is that the Linestring geojson object shows only one point which is wrong because a line must have at least two points. Again, probably an error in my implementation.

**Comment by mehdisadeghi** [comment]
@carocad so we need a more precise test for `directions` function then.

**Comment by carocad** [comment]
@mehdisadeghi by specifying a spec for a function we automatically get tests for those. See the [instrumentation and testing](https://clojure.org/guides/spec#_instrumentation_and_testing) section of clojure spec.

On the other hand we could also just define a test for that based on the spec. See the `prop_test` file on the test folder.

Obviously more tests would be nice but since the directions functions is hardly finished I just left that topic open :D

**Comment by mehdisadeghi** [comment]
> The distance and duration can be zero if the start and end are the same. 

Is it possible to fit this in the specs?

> The other problem is that the Linestring geojson object shows only one point which is wrong because a line must have at least two points.

Again spec question, can we set special specs for "LineString"?

**Comment by carocad** [comment]
> Is it possible to fit this in the specs?

Possible but not worth the effort. I think simply making the distance as equal or greater than zero is enough just like you said.

> Again spec question, can we set special specs for "LineString"?

Yes this is completely normal for specs definition. In fact I already did it for the geojson spec used in `hive`. I guess it would probably be easier to just publish it as a library and be done with it instead copying things around so much 

https://github.com/n7a235/app.hive/blob/master/src/hive/geojson.cljs#L33

**Comment by carocad** [comment]
I think this was fixed in https://github.com/n7a235/service.routing/pull/47

There were some spec and miscelaneous fixed in there
